### ISSUE TITLE
Came across a FIT file that cannot be parsed

### ISSUE THREAD

**Issue by haualan** [dtcooper/python-fitparse#38]
[2017-10-04-20-03-29.fit.zip](https://github.com/dtcooper/python-fitparse/files/1360252/2017-10-04-20-03-29.fit.zip)
I came across a fit file that cannot be successfully parsed but it appears that the file can be imported by other libs like Golden Cheetah so I thought I would bring it to your attention.

Here are the logs from the error when i try to parse the file.
`
Traceback (most recent call last):
  File "fitparseTest.py", line 7, in <module>
    for record in fitfile.get_messages('record'):
  File "/Users/wingchiuhau/.virtualenvs/testfit/lib/python2.7/site-packages/fitparse/base.py", line 450, in get_messages
    message = self._parse_message()
  File "/Users/wingchiuhau/.virtualenvs/testfit/lib/python2.7/site-packages/fitparse/base.py", line 160, in _parse_message
    message = self._parse_data_message(header)
  File "/Users/wingchiuhau/.virtualenvs/testfit/lib/python2.7/site-packages/fitparse/base.py", line 340, in _parse_data_message
    cmp_raw_value, accumulator[component.def_num], component.bits,
  File "/Users/wingchiuhau/.virtualenvs/testfit/lib/python2.7/site-packages/fitparse/base.py", line 307, in _apply_compressed_accumulation
    base_value = raw_value + (accumulation & ~max_mask)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
`

**Comment by pR0Ps** [comment]
Thanks for the report, I've confirmed the issue in both Python 2.7.13 and 3.6.0. Would you mind if this file was added to the repository as a test case?

**Comment by haualan** [comment]
Not at all. Feel free to use the file for test case.

On Oct 6, 2017 21:03, "Carey Metcalfe" <notifications@github.com> wrote:

Thanks for the report, I've confirmed the issue in both Python 2.7.13 and
3.6.0. Would you mind if this file was added to the repository as a test
case?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dtcooper/python-fitparse/issues/38#issuecomment-334748484>,
or mute the thread
