### ISSUE TITLE
Ubuntu 12.04.5 LTS error

### ISSUE THREAD

**Issue by F3L1X79** [dtcooper/python-fitparse#42]
I'm not quite sure if this is a real issue, but I had no problem to run a script on macOs localhost,
but when running in production on a Ubuntu 12.04.5 LTS server, I got this error:

```
Traceback (most recent call last):
  File "/path/to/myscript.py", line 10, in <module>
    for record in fitfile.get_messages('record'):
  File "/usr/local/lib/python2.7/dist-packages/fitparse/base.py", line 450, in get_messages
    message = self._parse_message()
  File "/usr/local/lib/python2.7/dist-packages/fitparse/base.py", line 160, in _parse_message
    message = self._parse_data_message(header)
  File "/usr/local/lib/python2.7/dist-packages/fitparse/base.py", line 318, in _parse_data_message
    header.local_mesg_num))
fitparse.utils.FitParseError: Got data message with invalid local message type 11
```

I'm asking for some help if you got any idea about this? Many thanks.

**Comment by pR0Ps** [comment]
Could you post the file that caused this as well as your Python version?

**Comment by F3L1X79** [comment]
Sure,
Python 2.7.3

myscript.py:
```
from fitparse import FitFile
import datetime
import sys
import json

fitfile = FitFile(sys.argv[1])

# Get all data messages that are of type record
records=[]
for record in fitfile.get_messages('record'):

    # Go through all the data entries in this record
    activities=[]
    activity_line={}
    for record_data in record:
        value = record_data.value
		
        if isinstance(value, datetime.datetime):
            value = record_data.value.strftime("%Y-%m-%d %H:%M:%S")
			
        activity_line[record_data.name] = value
        activities.append(activity_line)
		
    records.append(activities)
	
# Get all data messages that are of type lap
laps=[]
for record in fitfile.get_messages('lap'):

    # Go through all the data entries in this lap
    activities=[]
    activity_line={}
    for record_data in record:
        value = record_data.value
		
        if isinstance(value, datetime.datetime):
            value = record_data.value.strftime("%Y-%m-%d %H:%M:%S")
			
        activity_line[record_data.name] = value
        activities.append(activity_line)
		
    laps.append(activities)

output={'records':records, 'laps': laps}
print json.dumps(output)
```
[](https://developer.garmin.com/downloads/connect-api/sample_file.fit)

**Comment by F3L1X79** [comment]
JESUS, I'm so sorry, I may have corrupted the file because I cannot reproduce after re-downloading it...
So nervermind all of this and again: sorry!

Thank you for the good work by the way!! This library is really great!!
